export const chartWidgetsConfigMock = {
  widgetCommonConfig: {
    vitalsConfig: {
      vitalsConcepts: {
        SYSTOLIC_BLOOD_PRESSURE_CONCEPT: "5085AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
        DIASTOLIC_BLOOD_PRESSURE_CONCEPT:
          "5086AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
        PULSE_CONCEPT: "5087AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
        TEMPERATURE_CONCEPT: "5088AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
        OXYGENATION_CONCEPT: "5092AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
        HEIGHT_CONCEPT: "5090AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
        WEIGHT_CONCEPT: "5089AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
      },
      triageFormConfig: {
        formUuid: "a000cb34-9ec1-4344-a1c8-f692232f6edd",
        encounterTypeUuid: "67a71486-1a54-468f-ac3e-7091a9a79584"
      }
    }
  }
};
